# Generated by Django 6.0.5 on 2026-05-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('puzzle_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fen', models.TextField()),
                ('moves', models.TextField()),
                ('rating', models.IntegerField()),
                ('rating_deviation', models.IntegerField()),
                ('popularity', models.SmallIntegerField()),
                ('nb_plays', models.IntegerField()),
                ('themes', models.TextField()),
                ('game_url', models.URLField()),
                ('opening_tags', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'puzzle',
            },
        ),
    ]
