# Generated by Django 6.0.5 on 2026-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='rating',
            field=models.IntegerField(db_index=True),
        ),
    ]
